export const data = [
    {
        id: 12,
        image: "/assets/img/auctions/1.png",
        heart: true,
        name: "Tristique diam a, enim, eros tellus. Viverra etiam",
        x: true,
    },
    {
        id: 121,
        image: "/assets/img/auctions/2.png",
        heart: true,
        name: "Vulputate felis purus viverra morbi facilisi eget",
        x: true,
    },
    {
        id: 12123123,
        image: "/assets/img/auctions/3.png",
        heart: false,
        name: "Dui accumsan leo vestibulum ornare eu",
        x: true,
    },
    {
        id: 12128789,
        image: "/assets/img/auctions/4.png",
        heart: false,
        name: "Senectus adipiscing nascetur accumsan etiam",
        x: true,
    },
    {
        id: 112232,
        image: "/assets/img/auctions/5.png",
        heart: false,
        name: "Mattis at diam lorem nisl nam sed sociis",
        x: true,
    },
    {
        id: 1233,
        image: "/assets/img/sale/image.png",
        heart: false,
        name: "Mattis at diam lorem nisl nam sed sociis",
        x: false,
    },
    {
        id: 15552,
        image: "/assets/img/popular/1.png",
        heart: false,
        name: "Mattis at diam lorem nisl nam sed sociis",
        x: false,
    },
    {
        id: 124444,
        image: "/assets/img/popular/2.png",
        heart: false,
        name: "Mattis at diam lorem nisl nam sed sociis",
        x: false,
    },
    {
        id: 122331,
        image: "/assets/img/popular/3.png",
        heart: false,
        name: "Mattis at diam lorem nisl nam sed sociis",
        x: false,
    },
    {
        id: 9812,
        image: "/assets/img/popular/4.png",
        heart: false,
        name: "Mattis at diam lorem nisl nam sed sociis",
        x: false,
    },
    {
        id: 1992,
        image: "/assets/img/popular/5.png",
        heart: false,
        name: "Mattis at diam lorem nisl nam sed sociis",
        x: false,
    },
    {
        id: 15531772,
        image: "/assets/img/popular/6.png",
        heart: false,
        name: "Mattis at diam lorem nisl nam sed sociis",
        x: false,
    },
    {
        id: 121342,
        image: "/assets/img/popular/1.png",
        heart: false,
        name: "Mattis at diam lorem nisl nam sed sociis",
        x: false,
    },
    {
        id: 22,
        image: "/assets/img/popular/1.png",
        heart: false,
        name: "Mattis at diam lorem nisl nam sed sociis",
        x: false,
    },
    {
        id: 11512,
        image: "/assets/img/popular/1.png",
        heart: false,
        name: "Mattis at diam lorem nisl nam sed sociis",
        x: false,
    },
];
