import Head from "next/head";
import { useContext, useEffect } from "react";
import Banner from "../components/Banner";
import Card from "../components/Card";

// import data from "../data/data.json";
import { getData } from "../lib/getData";

import { ThemeContext, fetchData } from "../context/context";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
    const posts = await getData();
    return {
        props: { posts },
    };
}

export default function Home({ posts }) {
    const {
        value: { post },
        dispatch,
    } = useContext(ThemeContext);

    useEffect(() => {
        dispatch(fetchData(posts));
    }, [posts, dispatch]);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mt-5">
                <Banner />
                <div className="flex flex-wrap w-[1200px] mx-auto">
                    {post &&
                        post.map((e) => (
                            <Card key={e.id} {...e} href="detailtCard" />
                        ))}
                </div>
            </main>
        </div>
    );
}
